### ISSUE TITLE
[docs] Add firmware-upgrader quickstart

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-firmware-upgrader#108]
Create a build, explain categories, explain images, point out how to add custom firmware imags, explain OS identifier, point out list of available firmware images is incomplete.

**Comment by nemesisdesign** [comment]
Partially done in 3bdf95a45e93b42ed7677876856c069ced5f1f86, but I will leave it open to add some more screenshots and information to make it easier to follow.

**Comment by nemesisdesign** [comment]
Partially done in 3bdf95a45e93b42ed7677876856c069ced5f1f86, but I will leave it open to add some more screenshots and information to make it easier to follow. PS: help is welcome!

**Comment by OzgurBagci** [comment]
The documentation is vague related to custom images. 

- I don't see why the settings need the name of the firmware bin file. How is that name used in the system? Is it used for storing the file? Is it the expected filename to be uploaded related to the board? 
- In the case of Ansible, adding the related settings into YAML seems to be missing. It is not trivial to add custom image-related settings into YAML. 
- Lastly, I can guess where the board names are coming from in the OpenWRT source code, but the documentation on that part nevertheless proper.

**Comment by OzgurBagci** [comment]
For the interested parties, I was able to configure correctly via Ansible as below:

```
- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: _**<email_address>**_
    openwisp2_firmware_upgrader: true
    openwisp2_extra_django_settings:
      OPENWISP_USERS_AUTH_API: true
      OPENWISP_FIRMWARE_UPGRADER_API: true
      OPENWISP_CUSTOM_OPENWRT_IMAGES:
      - - _**<default_firmware_binary_name>**_
        - boards:
          - _**<menuconfig_board_name>**_
          label: _**<friendly_device_name>**_
```

It seems filename match is not needed while updating, but I manually selected the board. It may be needed when automatic detection is needed. The binary file name is probably the default firmware image name after image build. For the board name, I used the same name as `menuconfig`.
